version: '2'
services:
  web:
    build: .
    command: /bin/bash ./start.sh
    ports:
     - "8000:80"
    volumes:
     - .:/usr/share/nginx/html:rw
    depends_on:
     - db
  db:
    image: "postgres:9.5"
    volumes_from:
      - data
    ports:
     - "5432:5432"
  data:
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /var/lib/postgresql/data
